name: Go Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release Version'
        required: true
      prevVersion:
        description: 'Previous Tag'
        required: true
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17
      id: go

    # https://github.com/felixrieseberg/electron-wix-msi/issues/1#issuecomment-674598795
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
    # https://stackoverflow.com/a/64831469
    # https://github.community/t/set-path-for-wix-toolset-in-windows-runner/154708
    - name: Set WiX Toolset path for candle and light
      run: echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append


    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        ref: 'win-installer'

    - name: Get dependencies
      run: go get -v -t -d ./...
    
    - name: goversioninfo install
      run: go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo@latest
    - name: go-msi install
      run: go install github.com/mh-cbon/go-msi@latest

    - name: Release Build
      run: .\build.ps1 -release -ver ${{ github.event.inputs.releaseVersion }}
      shell: pwsh
      
    - name: Upload checksums
      uses: actions/upload-artifact@v2.2.2
      with:
        name: checksums
        path: checksums.md
        
    - name: Upload Binaries
      uses: actions/upload-artifact@v2.2.2
      with:
        name: release
        path: release/

  create_release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: Download Binaries
      uses: actions/download-artifact@v2
      with:
        name: release
    
    - name: Download Checksums
      uses: actions/download-artifact@v2.0.8
      with:
        name: checksums
      
    - name: Build Changelog
      id: build_changelog
      uses: heinrichreimer/github-changelog-generator-action@v2.1.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        sinceTag: ${{ github.events.inputs.prevVersion }}
        
    - name: Merge Body
      run: |
        echo "${{ steps.build_changelog.outputs.changelog}}" > changelog.md
        cat checksums.md >> changelog.md
        
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: changelog.md
        draft: true
        name: Release ${{ github.event.inputs.releaseVersion }}
        tag_name: ${{ github.event.inputs.releaseVersion }}
        files: |
          winssh-pageant-${{ github.event.inputs.releaseVersion }}_amd64.zip
          winssh-pageant-${{ github.event.inputs.releaseVersion }}_386.zip
          winssh-pageant-${{ github.event.inputs.releaseVersion }}_amd64.msi
          winssh-pageant-${{ github.event.inputs.releaseVersion }}_386.msi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}